#ifndef SH_ECS_IMPLEMENTATION_H
#define SH_ECS_IMPLEMENTATION_H

#define SH_ECS_MAX_ENTITIES 128
#define SH_ECS_MAX_COMPONENTS 24

#include "../../Externals/ShECS/ShECS/include/ShECS.h"

#endif // SH_ECS_IMPLEMENTATION